name: CI/CD Pipeline

on:
  push:
    paths:
      - index.html

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install proof-html
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby
        gem install proof-html

    - name: Validate HTML
      uses: chrisderivativ/w3c-html-validator-action@v1
      with:
        path: ./index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TUTORIAL_SECRET }}
        publish_dir: ./
